config/routes.rb
Rails.application.routes.draw do
  root "projects#index"
  resources :projects
  # get "projects" => "projects#index"
  # get "projects/:id" => "projects#show", as: "project"
  # get "projects/:id/edit" => "projects#edit", as: "edit_project"
  # patch "projects/:id" => "projects#update"
end

app/models/project.rb
class Project < ActiveRecord::Base

  def expired?
    Time.now > pledging_ends_on
  end

  def self.accepting_pledges
    where('pledging_ends_on >= ?', Time.now).order('pledging_ends_on')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = Project.accepting_pledges
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to @project
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to @project
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :target_pledge_amount, :website, :pledging_ends_on, :team_members, :image_file_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def format_pledge_end(project)
    if project.expired?
      content_tag(:strong, "All Done!")
    else
      distance_of_time_in_words(Time.now, project.pledging_ends_on)
    end
  end

  def image_for(project)
    if project.image_file_name.blank?
      image_tag('project.png', :size => '110x110')
    else
      image_tag(project.image_file_name, :size => '110x110')
    end
  end
  
end

app/views/layouts/_footer.html.erb
<footer style = "background: #D2B48C; padding: 3px">
  <p>
    Copyright &copy; 2015 
    <%= link_to("Bank of Shaun", 'www.espn.com') %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id='page-header'>
  <h1>Small Business Niche Funding</h1>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li>
        <%= link_to 'All Projects', projects_path %>
      </li>
      <li>
        <%= link_to 'Add New Project', new_project_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Niche Funding</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= render 'layouts/sidebar' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols: 40, rows: 5 %>
  </p>
  <p>
    <%= f.label :target_pledge_amount %><br/>
    <%= f.text_field :target_pledge_amount %>
  </p>
  <p>
    <%= f.label :pledging_ends_on %><br/>
    <%= f.date_select :pledging_ends_on %>
  </p>
  <p>
    <%= f.label :website %><br/>
    <%= f.text_field :website, size: 40 %>
  </p>  
  <p>
    <%= f.label :team_members %><br/>
    <%= f.text_field :team_members %>
  </p>
  <p>
    <%= f.label :image_file_name %><br/>
    <%= f.text_field :image_file_name %>
  </p>
  <p>
    <%= f.submit %> | <%= link_to('Cancel', projects_path) %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project: <%= @project.name %></h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1><%= pluralize(@projects.size, 'Project') %></h1>

<% @projects.each do |project| %>
  <article class ="project">
    <header>
      <h2><%= link_to(project.name, project) %>
      </h2>
      <%= image_for(project) %>
    </header>
    <p>
      <%= truncate(project.description, length: 150) %>
    </p>
    <table>
      <tr>
        <th>Target Pledge Amount:</th>
        <td><%= number_to_currency(project.target_pledge_amount) %></td>
      </tr>
      <tr>
        <th>Website:</th>
        <td><%= project.website %></td>
      </tr>
      <tr>
        <th>Pledging Ends:</th>
        <td><%= format_pledge_end(project) %> remaining</td>
      </tr>
    </table>
  </article>
<% end %>

app/views/projects/new.html.erb
<h1>Project Creation</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<article>
  <header>
    <h1><%= @project.name %></h1>
    <%= image_for(@project) %>
  </header>
  <h2>Description:</h2>
  <p>
    <%= @project.description %>
  </p>
  <h3>Pledge Goal:</h3>
  <p>
    <%= number_to_currency(@project.target_pledge_amount) %>
  </p>
  <h3>Pledge End Date:</h3>
  <p>
    <%= format_pledge_end(@project) %> remaining
  </p>
  <h3>Website:</h3>
  <p>
    <%= @project.website %>
  </p>
  <h3>Team Members:</h3>
  <p>
    <%= pluralize(@project.team_members, 'Team Member') %>
  </p>
</article>

<%= link_to("Edit", edit_project_path) %> |
<%= link_to("Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure"}) %>